export const GET_PRICES_SUCCESS = "GET_PRICES_SUCCESS";
export const GET_PRICES_FAILURE = "GET_PRICES_FAILURE";
export const GET_PRICES_REQUEST = "GET_PRICES_REQUEST";
export const SELECT_ROW = "SELECT_ROW";
export const DESELECT_ROW = "DESELECT_ROW";
export const UPDATE_CURRENCY_QUERY = "UPDATE_CURRENCY_QUERY";
export const UPDATE_DATE_QUERY = "UPDATE_DATE_QUERY";
